.env.local
.eslintrc.cjs
.github/workflows/ci.yml
.github/workflows/ci_frontend.yml
README.md
jest.config.mjs
jest.setup.js
package-lock.json
package.json
server.js
src/app/api/[userId]/raspberry-pi/route.ts
src/app/api/raspberrypi/data/route.js
src/app/api/socket/route.js
src/app/api/test/route.test.js
src/app/dashboard/page.tsx
src/app/layout.tsx
src/app/models/notification.js
src/app/models/raspberryPi.js
src/app/models/sensorData.js
src/app/models/user.js
src/components/dashboard/DashboardCharts.jsx
src/components/dashboard/SensorChart.jsx
src/hooks/useSocket.js
src/lib/mongodb.js
src/lib/socket.js
start-dev.bat
test-socket-api.js
test-socket.bat
test/integration/api.spec.js
test/integration/test-route.js
