name: CD Pipeline

on:
  pull_request:
    branches:
      - main # Trigger only on PR targeting 'main'
  workflow_run:
    workflows: ['CI Backend', 'CI Frontend']
    types:
      - completed # Trigger when the CI workflows are completed
  workflow_dispatch:

jobs:
  check-ci-status:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Fetch workflow status
        id: fetch_status
        run: |
          echo "CI Backend status: ${{ github.event.workflow_run.conclusion }}"
          echo "CI Frontend status: ${{ github.event.workflow_run.conclusion }}"

  deploy:
    runs-on: ubuntu-latest
    needs: check-ci-status # Deploy only happens if check-ci-status passes
    if: ${{ needs.check-ci-status.result == 'success' }} # Ensure it only runs if the CI passed
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

        # Todo
      - name: Deploy application
        run: |
          echo "Deploying application..."
